export const TODO_LIST_REQUEST = 'TODO_LIST_REQUEST';
export const TODO_LIST_SUCCESS = 'TODO_LIST_SUCCESS';
export const TODO_LIST_FAIL = 'TODO_LIST_FAIL';
export const TODO_DELETE_ITEM = 'TODO_DELETE_ITEM';
export const TODO_UPDATE_ITEM = 'TODO_UPDATE_ITEM';
export const TODO_COMPLETE_ITEM = 'TODO_COMPLETE_ITEM';
