export const PHOTO_LIST_REQUEST = 'PHOTO_LIST_REQUEST';
export const PHOTO_LIST_SUCCESS = 'PHOTO_LIST_SUCCESS';
export const PHOTO_LIST_FAIL = 'PHOTO_LIST_FAIL';
export const FILTER_PHOTO_LIST = 'FILTER_PHOTO_LIST';
